name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: generate project
      run: mkdir .build && cd .build && cmake ..
    - name: build
      run: cmake --build .build --target AeroJet
      
      
  build-windows:
      
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3e
    - name: generate project
      run: mkdir .build && cd .build && cmake ..
    - name: build
      run: cmake --build .build --target AeroJet
      
  build-osx:
      
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: generate project
      run: mkdir .build && cd .build && cmake ..
    - name: build
      run: cmake --build .build --target AeroJet
