name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-tests:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: generate project
      run: mkdir .build && cd .build && cmake ..
    - name: build
      run: cmake --build .build --target all
    - name: test
      run: cd .build && ctest --extra-verbose
      
